# ---------------------------------------
# Settings for the experiments with the
# TUT SED Real Life 2017 dataset.
#
# author: Konstantinos Drossos,
#         Tampere University
# ---------------------------------------
#
# Settings for the data loading
data_loader:
  batch_size: 8
  shuffle: Yes
  drop_last: Yes
  root_dir: 'dataset'
  scene:  # Not used in the TUT SED Real Life 2017 dataset
  data_fold:  # Is set dynamically in the experiments
  data_version: 'synthetic'
#
# Settings for the optimizer
optimizer:
  lr: !!float 1e-4
#
# Settings for the training process
training:
  epochs: 200
  validation_patience: 50
  grad_norm: .5
#
# Settings for the SED model
sed_model:
  nb_labels: 6
  cnn_channels: 256
  cnn_dropout: .25
  rnn_dropout: .25
#
# Settings for the teacher forcing
tf:
  gamma_factor: 10
  mul_factor: 80
  min_prob: .05
  max_prob: .9

# EOF
